[package]
name = "rustcamp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = {version = "0.3.34", features = ["formatting", "macros", "parsing"]}
rand = "0.8.5"
rayon = "1.9.0"